### ISSUE TITLE
ctor.requireAsync is not a function error

### ISSUE THREAD

**Issue by HakanSungur** [gregberge/loadable-components#1008]
"react": "^17.0.2"
 "react-dom": "^17.0.2"

´´´ import loadable from '@loadable/component'

const SectionBecomeAnAuthor = loadable(() => import('../../components/SectionBecomeAnAuthor/SectionBecomeAnAuthor'))
´´´
Uncaught TypeError: ctor.requireAsync is not a function
    at cachedLoad (loadable.esm.mjs:140:1)
    at InnerLoadable.resolveAsync (loadable.esm.mjs:353:1)
    at InnerLoadable.loadAsync (loadable.esm.mjs:323:1)
    at InnerLoadable.componentDidMount (loadable.esm.mjs:230:1)
    at commitLifeCycles (react-dom.development.js:20663:1)
    at commitLayoutEffects (react-dom.development.js:23426:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:98:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at commitRootImpl (react-dom.development.js:23151:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at commitRoot (react-dom.development.js:22990:1)
    at performSyncWorkOnRoot (react-dom.development.js:22329:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)

I would appreciate it if you could help me with this error.

**Comment by theKashey** [comment]
Sounds like babel plugin is absent.
