### ISSUE TITLE
How loadable-component works with SSR and React Router

### ISSUE THREAD

**Issue by kapilgp** [gregberge/loadable-components#612]
## 💬 How loadable-component works with SSR and React Router

We are trying to use this into our project but we are getting issue with SSR and React Router. It works great with SSR without React Router.

I just change the following thing in your example server-side-rendering src/client/App.js

```
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';

const App = () => (
  <div>
  <Router>
    <Switch>
      <Route exact path="/" component={A}/>
      <Route path="/letter-b" component={B}/>
    </Switch>
  </Router>
  </div>
);

```

After that when I try to run code it gives following error.

> Server started http://localhost:9000
Error: Invariant failed
    at invariant (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:11:15)
    at Object.createBrowserHistory (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/history/cjs/history.min.js:1:3677)
    at new e (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/react-router-dom/cjs/react-router-dom.min.js:1:1036)
    at d (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at /home/kapil/Projects/loadable-components/examples/server-side-rendering/lib/server/main.js:57:43
    at Layer.handle [as handle_request] (/home/kapil/Projects/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/layer.js:95:5)

**Comment by theKashey** [comment]
You cannot use BrowserRouter on the server. Please refer to react-router documentation about the usage of StaticRouter and integration with some particular webserver middleware (ie passing "current url")
https://reactrouter.com/web/api/StaticRouter

**Comment by kapilgp** [comment]
Thanks @theKashey, It works now.
