### ISSUE TITLE
Can't launch SSR example

### ISSUE THREAD

**Issue by astnt** [gregberge/loadable-components#693]
## 🐛 Bug Report

I'm trying to launch SSR example.

## To Reproduce

Follow https://github.com/gregberge/loadable-components/blob/master/examples/server-side-rendering/README.md instructions.

## Expected behavior

Example will start to work.

## Link to repl or repo (highly encouraged)

https://github.com/gregberge/loadable-components/tree/master/examples/server-side-rendering

Exception:

```
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node src/server/main.js`
/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@babel/core/lib/config/files/plugins.js:175
    throw e;
    ^

Error: Cannot find module '/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@loadable/babel-plugin/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:318:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:700:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at resolve (internal/modules/cjs/helpers.js:78:19)
    at resolveStandardizedName (/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@babel/core/lib/config/files/plugins.js:100:7)
    at resolvePlugin (/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@babel/core/lib/config/files/plugins.js:44:10)
    at loadPlugin (/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at createDescriptor (/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/user/WebstormProjects/loadable-components/examples/server-side-rendering/node_modules/@loadable/babel-plugin/package.json',
  requestPath: '@loadable/babel-plugin'
}
[nodemon] app crashed - waiting for file changes before starting...
```

```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 - Memory: 275.84 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 13.11.0 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.13.7 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by lmreicks** [comment]
Try building the whole library before using the example. The issue is the "main" in babel-plugin package.json is pointing to lib/main.js which only exists after the package is built.
