### ISSUE TITLE
Error with "path"

### ISSUE THREAD

**Issue by MasterCPP** [gregberge/loadable-components#791]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.extname (path.js:1365:5)
    at getFileScriptType (/home/lemit/loadable-components/examples/server-side-rendering-async-node/node_modules/@loadable/server/lib/ChunkExtractor.js:49:60)
    at isScriptFile (/home/lemit/loadable-components/examples/server-side-rendering-async-node/node_modules/@loadable/server/lib/ChunkExtractor.js:53:10)
    at stats.assets.filter (/home/lemit/loadable-components/examples/server-side-rendering-async-node/node_modules/@loadable/server/lib/ChunkExtractor.js:366:11)
    at Array.filter (<anonymous>)
    at ChunkExtractor.requireEntrypoint (/home/lemit/loadable-components/examples/server-side-rendering-async-node/node_modules/@loadable/server/lib/ChunkExtractor.js:364:23)
    at app.get (/home/lemit/loadable-components/examples/server-side-rendering-async-node/src/server/main.js:43:42)
    at Layer.handle [as handle_request] (/home/lemit/loadable-components/examples/server-side-rendering-async-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lemit/loadable-components/examples/server-side-rendering-async-node/node_modules/express/lib/router/route.js:137:13)

**Comment by theKashey** [comment]
It was not very easy to understand that in order to reproduce it all I need is to run [loadable-components/examples/server-side-rendering-async-node](https://github.com/gregberge/loadable-components/tree/main/examples/server-side-rendering-async-node).

I will double-check if there are any problems.

As you've skipped the issue template, I have to close this one. Please try to valuable time of maintainers and invest a little more efforts from your side.
