### ISSUE TITLE
requireEntrypoint broken on Webpack 5

### ISSUE THREAD

**Issue by polkovnikov-ph** [gregberge/loadable-components#794]
## 🐛 Bug Report

[`compilation.getStats()`](https://github.com/gregberge/loadable-components/blob/main/packages/webpack-plugin/src/index.js#L22) doesn't return whatever it returned previously. Now corresponding object in `loadable-stats` file looks like this:

```ts
  "assets": [
    {
      "type": "assets by status",
      "cached": true,
      "filteredChildren": 4,
      "size": 98968
    }
  ],
```

Monkey-patching `assets` prior to `new ChunkExtractor` in this way helps:

```ts
const stats = JSON.parse(memfs.readFileSync(statsFile));
stats.assets = Object.values(stats.namedChunkGroups);
const nodeExtractor = new ChunkExtractor({ stats });
const foo = nodeExtractor.requireEntrypoint();
```

## To Reproduce

1. `requireEntrypoint`
2. 
```ts
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at Object.extname (node:path:837:5)
    at getFileScriptType (PROJECT\node_modules\@loadable\server\lib\ChunkExtractor.js:49:60)
    at isScriptFile (PROJECT\node_modules\@loadable\server\lib\ChunkExtractor.js:53:10)
    at PROJECT\node_modules\@loadable\server\lib\ChunkExtractor.js:367:11
    at Array.filter (<anonymous>)
    at ChunkExtractor.requireEntrypoint (PROJECT\node_modules\@loadable\server\lib\ChunkExtractor.js:365:23)
```

## Expected behavior

No error.

## Link to repl or repo (highly encouraged)

Hopefully I've given enough information to reproduce. Otherwise let it stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Windows 10
## Binaries:
 - Node: 16.2.0
 - npm: 7.13.0
## npmPackages:
 - @loadable/babel-plugin: 5.13.2 => 5.13.2
 - @loadable/component: 5.15.0 => 5.15.0
 - @loadable/server: 5.15.0 => 5.15.0
 - @loadable/webpack-plugin: 5.15.0 => 5.15.0
```

**Comment by theKashey** [comment]
Related: #791, #770

**Comment by apizzini** [comment]
I'm experiencing the same issue and #779 fixes it (thanks @depoulo).

@theKashey any chance we can get a release cut with this fix in please?

**Comment by loks0n** [comment]
#779 works great.
Does anyone have an intermediate solution whilst we wait for the release?

**Comment by depoulo** [comment]
> #779 works great.
> Does anyone have an intermediate solution whilst we wait for the release?

Quoting https://github.com/gregberge/loadable-components/issues/770#issuecomment-848551220:

I also published an according git tag to be used with npm / yarn: https://github.com/depoulo/loadable-components/tree/%40loadable/webpack-plugin%2Fcached-assets-770%2F5.15.1
