### ISSUE TITLE
require of pure ESM module is not supported

### ISSUE THREAD

**Issue by ucarbehlul** [gregberge/loadable-components#913]
I am trying to use https://github.com/remarkjs/react-markdown#install (pure ESM package) in my project that is set up with loadable-components but on the server side I am getting an error like:

```
loadable-components: failed to synchronously load component, which expected to be available {
  fileName: '/Users/behlul/dev/project/client/src/client/pages/Page.js',
  chunkName: 'pages-Page',
  error: 'require() of ES Module /Users/behlul/dev/project/client/node_modules/react-markdown/index.js from /Users/behlul/dev/project/client/src/client/pages/Page.js not supported.\n' +
    'Instead change the require of index.js in /Users/behlul/dev/project/client/src/client/pages/Page.js to a dynamic import() which is available in all CommonJS modules.'
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/behlul/dev/project/client/node_modules/react-markdown/index.js from /Users/behlul/dev/project/client/src/client/pages/Page.js not supported.
Instead change the require of index.js in /Users/behlul/dev/project/client/src/client/pages/Page.js to a dynamic import() which is available in all CommonJS modules.
    at Object.newLoader [as .js] (/Users/behlul/dev/project/client/node_modules/pirates/lib/index.js:104:7)
    at Object.<anonymous> (/Users/behlul/dev/project/client/src/client/pages/Page.js:24:45)
```

My babel config is like below:
```
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "edge": "17",
          "firefox": "60",
          "chrome": "67",
          "safari": "11.1"
        },
        "useBuiltIns": "usage",
        "corejs": "3.6.4"
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-syntax-export-default-from",
    "@loadable/babel-plugin"
  ]
}
```

What can be the issue here? Or to put it in other way, how can we use pure ESM modules with loadable?

**Comment by theKashey** [comment]
The error is

> require() of ES Module /Users/behlul/dev/project/client/node_modules/react-markdown/index.js from /Users/behlul/dev/project/client/src/client/pages/Page.js not supported.

The proposed solution is to use dynamic import, but the problem is we need to _to synchronously load component_, which is not possible using dynamic import.

-----

The origin of the problem is `nodejs` and your webpack configuration marking all `node_modules` as external, thus keeping them under nodejs control. And this is a setting you want to have.

A solution i can propose and the one you need to check - try to hide this dependency behind a local file
- `src/client/pages/Page.js` -> `loadable(() => import('../../services/react-markdown'))`
- ⬇️ "indirection" ⬇️
- `src/services/react-markdown` -> `export { default } from 'react-markdown'`;

However I am not sure that will work. ESM modules are not really supposed to be "required" even via _indirection_.

If this trick will not work for you - try [imported-component](https://github.com/theKashey/react-imported-component) as it does not transform imports (by the cost of importing everything at server side)

**Comment by ucarbehlul** [comment]
Thanks, I ended up using webpack to transpile the esm modules that created the issue. 

here is an example webpack 4 config that would transpile some node_modules and create a bundle with them for SSR (probably it has some unnecessary things such as loadable plugin as i didn't optimize it fully but it got the job done):
```
var path = require("path")
const nodeExternals = require('webpack-node-externals')
const LoadablePlugin = require('@loadable/webpack-plugin')

const paths = require('./config/paths');
console.debug("Paths are:", paths)

const imageInlineSizeLimit = parseInt(
  process.env.IMAGE_INLINE_SIZE_LIMIT || '10000'
)

var commonLoaders = [
	{ test: /\.js$/, loader: "jsx-loader" },
	{ test: /\.png$/, loader: "url-loader" },
	{ test: /\.jpg$/, loader: "file-loader" },
];

var outputPath = path.join(__dirname, "build-server")
var publicPath = "assets/"

const isEnvProduction = true;

module.exports = [
	{
		// The configuration for the server-side rendering
		name: "server-side rendering",
		entry: "./src/server/app.js",
		target: "node",
		output: {
			path: outputPath,
			filename: "bundle.js",
			publicPath: publicPath,
      library: "server",
      libraryExport: 'default',
			libraryTarget: "commonjs"
		},
		externals: [nodeExternals({
      allowlist: ["react-markdown", /vfile/, "unified", "bail", "is-plain-obj",
        "trough", "remark-parse", /micromark/, "decode-named-character-reference", 
        "character-entities", /remark/, /mdast/, /unist/, /trim-lines/, 
        /property-information/, /hast/, "space-separated-tokens", "comma-separated-tokens",
        /ccount/, /markdown/ 
      ]
    })],
		module: {
      strictExportPresence: true,
      rules: [
        // Disable require.ensure as it's not a standard language feature.
        { parser: { requireEnsure: false } },

        // First, run the linter.
        // It's important to do this before Babel processes the JS.
        {
          test: /\.(js|mjs|jsx|ts|tsx)$/,
          enforce: 'pre',
          use: [
            {
              options: {
                cache: true,
                formatter: require.resolve('react-dev-utils/eslintFormatter'),
                eslintPath: require.resolve('eslint'),
                resolvePluginsRelativeTo: __dirname,
                
              },
              loader: require.resolve('eslint-loader'),
            },
          ],
          include: paths.appSrc,
        },
        {
          // "oneOf" will traverse all following loaders until one will
          // match the requirements. When no loader matches it will fall
          // back to the "file" loader at the end of the loader list.
          oneOf: [
            // "url" loader works like "file" loader except that it embeds assets
            // smaller than specified limit in bytes as data URLs to avoid requests.
            // A missing `test` is equivalent to a match.
            {
              test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
              loader: require.resolve('url-loader'),
              options: {
                limit: imageInlineSizeLimit,
                name: 'static/media/[name].[hash:8].[ext]',
              },
            },
            // Process application JS with Babel.
            // The preset includes JSX, Flow, TypeScript, and some ESnext features.
            {
              test: /\.(js|mjs|jsx|ts|tsx)$/,
              loader: require.resolve('babel-loader'),
              options: {
                presets: [
                  [
                    "@babel/env",
                    {
                      "targets": {
                        "edge": "17",
                        "firefox": "60",
                        "chrome": "67",
                        "safari": "11.1"
                      },
                      "useBuiltIns": "usage",
                      "corejs": "3.6.4"
                    }
                  ],
                  "@babel/preset-react",
                  "@babel/preset-typescript"
                 ],
                plugins: [
                   "@babel/plugin-syntax-export-default-from",
                   "@loadable/babel-plugin"
                ],
                // This is a feature of `babel-loader` for webpack (not Babel itself).
                // It enables caching results in ./node_modules/.cache/babel-loader/
                // directory for faster rebuilds.
                cacheDirectory: true,
                // See #6846 for context on why cacheCompression is disabled
                cacheCompression: false,
                compact: isEnvProduction,
              },
            },
          ],
        }
      ], 
    },
    plugins: [
      new LoadablePlugin()
    ]
	}
]
```

after this i could run the app as node `build-server/bundle.js` and loadable-components worked with no issues. build-server is still only 232 kb so seems like a good solution unless there are tons of node_modules to transpile.
